
spring:
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: ecs-ppt4-conta
      topic: comando-abrir-conta
      enable-auto-commit: false  # Desabilita o commit automático
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
api:
  header:
    api-key: "d97a2a44-7dec-4dcf-bcc7-3df1d41b7dd6"
  base-url:
    pessoa: http://localhost:3000
  time:
    ms: 10

management:
  endpoints:
    web:
      exposure:
        include: [ "prometheus" ]

#logging:
#  level:
#    org:
#      springframework: DEBUG